#!/bin/bash
set -e

# Remove a potentially pre-existing server.pid for Rails.
rm -f /railsapp/tmp/pids/server.pid

cd /railsapp
# Exec migrations and seeds
# De momento lo comentamos para poder acelerar la carga del servicio
if [ "${RUN_MIGRATIONS:-false}" == "true" ]
then
  rake db:migrate
  rake db:seed
fi

# Then exec the container's main process (what's set as CMD in the Dockerfile).
exec "$@"
